### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Astudnew** [Dhanachandra/bert-crf4NER#4]
Hi
I clone your repo on google colab to run it
At  the  beginning I get an error that torchcrf module not found but after I install   pytorch-crf (!pip install pytorch-crf==0.4.0) it works , but I get other errors :
"Traceback (most recent call last):
  File "bert_crf.py", line 433, in <module>
    t_loss, v_loss = train(train_iter, eval_iter, tag2idx, config=config, bert_model=config.bert_model)
  File "bert_crf.py", line 196, in train
    model = Bert_CRF.from_pretrained(bert_model, num_labels = len(tag2idx))
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py", line 1034, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "bert_crf.py", line 141, in __init__
    self.crf = CRF(self.num_labels, batch_first=True)    
TypeError: __init__() got an unexpected keyword argument 'batch_firs"
how I can fix them?

**Comment by Phd-Student2018** [comment]
also this error
File "bert_crf.py", line 434, in <module>
    t_loss, v_loss = train(train_iter, eval_iter, tag2idx, config=config, bert_model=config.bert_model)
  File "bert_crf.py", line 235, in train
    loss= model(**inputs) 
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "bert_crf.py", line 151, in forward
    loss = -self.crf(log_soft(emission, 2), labels, mask=attn_masks, reduction='mean')
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'reduction'
Epoch:   0% 0/5 [00:00<?, ?it/s]
